# Generated by Django 3.1.12 on 2025-08-22 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('camera_id', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detection_sessions',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('epochs', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=16)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('current_epoch', models.IntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('training_loss', models.FloatField(default=0.0)),
                ('validation_loss', models.FloatField(default=0.0)),
                ('model_weights_path', models.CharField(blank=True, max_length=500)),
                ('training_log_path', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HelmetDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('camera_id', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.CharField(max_length=500)),
                ('processed_image', models.CharField(blank=True, max_length=500)),
                ('person_detected', models.BooleanField(default=False)),
                ('person_confidence', models.FloatField(default=0.0)),
                ('person_bbox', models.JSONField(default=dict)),
                ('helmet_detected', models.BooleanField(default=False)),
                ('helmet_confidence', models.FloatField(default=0.0)),
                ('helmet_bbox', models.JSONField(default=dict)),
                ('vehicle_detected', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_bbox', models.JSONField(default=dict)),
                ('plate_detected', models.BooleanField(default=False)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('plate_confidence', models.FloatField(default=0.0)),
                ('plate_bbox', models.JSONField(default=dict)),
                ('is_violation', models.BooleanField(default=False)),
                ('violation_type', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livedetection.detectionsession')),
            ],
            options={
                'db_table': 'helmet_detections',
                'ordering': ['-timestamp'],
            },
        ),
    ]
